/* ultimate-frontend-skills - CREDITS.md, generated from the data.

   Every site the reference corpus names, and every pack this plugin defers to,
   with the people behind them, so that the work this plugin learns from is
   visible where anyone can see it. Nothing here is copied from those sites; the
   corpus is data used to pick references to look at.

     credits            write CREDITS.md
     credits --check    exit 1 if CREDITS.md is stale (run in tests) */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const DATA = join(ROOT, 'skills', 'ultimate-frontend-skills', 'data');
export const OUT = join(ROOT, 'CREDITS.md');

const SOURCE_NAMES = {
  awwwards: 'Awwwards', fwa: 'FWA', cssda: 'CSS Design Awards', codrops: 'Codrops', threejs: 'three.js showcase',
  godly: 'Godly', 'land-book': 'Land-book', siteinspire: 'siteInspire', onepagelove: 'One Page Love', studio: 'Studios',
  game: 'Games', app: 'Apps', reference: 'Reference sites',
};

export function render() {
  const corpus = JSON.parse(readFileSync(join(DATA, 'awards.json'), 'utf8'));
  const packs = existsSync(join(DATA, 'packs.json')) ? JSON.parse(readFileSync(join(DATA, 'packs.json'), 'utf8')) : [];
  const bySource = new Map();
  for (const e of corpus) {
    const key = String(e.source || 'reference').toLowerCase();
    if (!bySource.has(key)) bySource.set(key, []);
    bySource.get(key).push(e);
  }
  const lines = ['# Credits', '',
    "This plugin learns from other people's work, and this file says whose. Every",
    'site below is in the reference corpus (data/awards.json), picked so a model',
    'can look at a real thing before it decides; nothing is copied from any of them.',
    'The packs are the third-party skills the plugin defers to when they are',
    'installed. Generated by webdesign.mjs credits; do not edit by hand.', '',
    '## Packs', ''];
  for (const p of packs) {
    const url = p.kind === 'plugin' && p.marketplace === 'claude-plugins-official' ? 'https://github.com/anthropics/claude-plugins-official' : 'https://github.com/' + p.id.split('@')[0];
    lines.push('- [' + p.id + '](' + url + ')' + (p.licence ? ' - ' + p.licence : '') + ' - ' + (p.owns || ''));
  }
  const order = [...bySource.keys()].sort((a, b) => bySource.get(b).length - bySource.get(a).length);
  for (const key of order) {
    const rows = bySource.get(key).slice().sort((a, b) => String(a.name).localeCompare(String(b.name)));
    lines.push('', '## ' + (SOURCE_NAMES[key] || key) + ' (' + rows.length + ')', '');
    for (const e of rows) {
      const who = [e.studio, e.year].filter(Boolean).join(', ');
      lines.push('- [' + e.name + '](' + e.url + ')' + (who ? ' - ' + who : '') + (e.award && e.award !== 'reference' ? ' - ' + e.award : '') + (e.dead ? ' (offline when last checked)' : ''));
    }
  }
  lines.push('', corpus.length + ' sites, ' + packs.length + ' packs.', '');
  return lines.join('\n');
}

const invoked = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (invoked) {
  const text = render();
  if (process.argv.includes('--check')) {
    const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
    if (cur.replace(/\r\n/g, '\n') !== text) { console.error('CREDITS.md is stale; run webdesign.mjs credits'); process.exit(1); }
    console.log('CREDITS.md is current');
  } else {
    writeFileSync(OUT, text);
    console.log('wrote ' + OUT);
  }
}
